name: CI - CPF Validator

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4  

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar testes
        run: pytest

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: zip -r projeto.zip .
      - uses: actions/upload-artifact@v4
        with:
          name: projeto-cpf
          path: projeto.zip
  notify:
    runs-on: ubuntu-latest
    needs: [test, build] # só roda depois que os outros jobs terminarem
    steps:
      - name: Enviar alerta para Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"🚨 Workflow finalizado no repositório *${{ github.repository }}* no commit ${{ github.sha }}. Status: ${{ job.status }}\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}       
